FROM node:20-alpine AS builder

WORKDIR /app

COPY ./frontend/package.json ./frontend/package-lock.json* ./

RUN npm ci

COPY ./frontend/ .

RUN npm run build

FROM nginx:stable-alpine

COPY --from=builder /app/build /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]